### ISSUE TITLE
issue when initial inclination = 0

### ISSUE THREAD

**Issue by tyy-cc** [GRIT-RBSim/GRIT#1]
Hi,

When the initial inclinations is exactly equal to zero, Omega and omega will be automatically set to Pi instead of their initial values which were set in "init_system.json". Is there any way to fix it? Thanks!

**Comment by babacry** [comment]
Hi tyy-cc,
The linked pull request above should have solved your issue.
Now, for orbital elements `(a,e,i,Omega,omega,anomaly)`,
if `i=0` and `e!=0`, then `Omega=0`, `omega=the angle between the reference direction (1,0,0) and the eccentricity vector`.
Best,
GRIT
